{% set name = "cms-combine" %}
{% set version = "10.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f198eaf93fbfef472ebf648ccba1bbc199ae9b415c16e7a4c7f6f5c8b9683550
  folder: HiggsAnalysis/CombinedLimit
  patches:
    - clang_warnings.patch
    - cmake_installpython.patch

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    - python
    - gsl

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - root_base                              # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - root_base
    - libboost-devel
    - eigen
    - vdt

  run:
    - python
    - pandas
    - six
    - gsl

test:
  source_files:
    - HiggsAnalysis/CombinedLimit/data/tutorials/multiDim/
    - HiggsAnalysis/CombinedLimit/data/tutorials/CAT23001/
  imports:
    - HiggsAnalysis.CombinedLimit.PhysicsModel
  commands:
    - combine -h
    - text2workspace.py -h

about:
  home: https://cms-analysis.github.io/HiggsAnalysis-CombinedLimit/
  summary: 'A software tool used for statistical analysis within the CMS experiment'
  description: |
    Combine is a RooStats / RooFit - based software tool used for statistical analysis within the
    CMS experiment. Note that while this tool was originally developed in the Higgs PAG, its usage
    is now widespread within CMS. Combine provides a command-line interface to many different statistical
    techniques, available inside RooFit/RooStats, that are used widely inside CMS.
  license: Apache-2.0
  license_family: Apache
  license_file: HiggsAnalysis/CombinedLimit/LICENSE
  doc_url: https://cms-analysis.github.io/HiggsAnalysis-CombinedLimit/
  dev_url: https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit

extra:
  recipe-maintainers:
    - nsmith-
    - anigamova
