# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

[project]
name = "cms-combine-feedstock"
version = "3.47.0"
description = "Pixi configuration for conda-forge/cms-combine-feedstock"
authors = ["@conda-forge/cms-combine"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
inspect-all = "inspect_artifacts --all-packages"
build = "rattler-build build --recipe recipe"
"build-linux_64_python3.10.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.10.____cpythonroot_base6.32.10.yaml"
"inspect-linux_64_python3.10.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.10.____cpythonroot_base6.32.10.yaml"
"build-linux_64_python3.10.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.10.____cpythonroot_base6.34.4.yaml"
"inspect-linux_64_python3.10.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.10.____cpythonroot_base6.34.4.yaml"
"build-linux_64_python3.11.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.11.____cpythonroot_base6.32.10.yaml"
"inspect-linux_64_python3.11.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.11.____cpythonroot_base6.32.10.yaml"
"build-linux_64_python3.11.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.11.____cpythonroot_base6.34.4.yaml"
"inspect-linux_64_python3.11.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.11.____cpythonroot_base6.34.4.yaml"
"build-linux_64_python3.12.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.12.____cpythonroot_base6.32.10.yaml"
"inspect-linux_64_python3.12.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.12.____cpythonroot_base6.32.10.yaml"
"build-linux_64_python3.12.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.12.____cpythonroot_base6.34.4.yaml"
"inspect-linux_64_python3.12.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.12.____cpythonroot_base6.34.4.yaml"
"build-linux_64_python3.9.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.9.____cpythonroot_base6.32.10.yaml"
"inspect-linux_64_python3.9.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.9.____cpythonroot_base6.32.10.yaml"
"build-linux_64_python3.9.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.9.____cpythonroot_base6.34.4.yaml"
"inspect-linux_64_python3.9.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.9.____cpythonroot_base6.34.4.yaml"
"build-osx_64_python3.10.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.10.____cpythonroot_base6.32.10.yaml"
"inspect-osx_64_python3.10.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.10.____cpythonroot_base6.32.10.yaml"
"build-osx_64_python3.10.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.10.____cpythonroot_base6.34.4.yaml"
"inspect-osx_64_python3.10.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.10.____cpythonroot_base6.34.4.yaml"
"build-osx_64_python3.11.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.11.____cpythonroot_base6.32.10.yaml"
"inspect-osx_64_python3.11.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.11.____cpythonroot_base6.32.10.yaml"
"build-osx_64_python3.11.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.11.____cpythonroot_base6.34.4.yaml"
"inspect-osx_64_python3.11.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.11.____cpythonroot_base6.34.4.yaml"
"build-osx_64_python3.12.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.12.____cpythonroot_base6.32.10.yaml"
"inspect-osx_64_python3.12.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.12.____cpythonroot_base6.32.10.yaml"
"build-osx_64_python3.12.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.12.____cpythonroot_base6.34.4.yaml"
"inspect-osx_64_python3.12.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.12.____cpythonroot_base6.34.4.yaml"
"build-osx_64_python3.9.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.9.____cpythonroot_base6.32.10.yaml"
"inspect-osx_64_python3.9.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.9.____cpythonroot_base6.32.10.yaml"
"build-osx_64_python3.9.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.9.____cpythonroot_base6.34.4.yaml"
"inspect-osx_64_python3.9.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.9.____cpythonroot_base6.34.4.yaml"
"build-osx_arm64_python3.10.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.10.____cpythonroot_base6.32.10.yaml"
"inspect-osx_arm64_python3.10.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.10.____cpythonroot_base6.32.10.yaml"
"build-osx_arm64_python3.10.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.10.____cpythonroot_base6.34.4.yaml"
"inspect-osx_arm64_python3.10.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.10.____cpythonroot_base6.34.4.yaml"
"build-osx_arm64_python3.11.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.11.____cpythonroot_base6.32.10.yaml"
"inspect-osx_arm64_python3.11.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.11.____cpythonroot_base6.32.10.yaml"
"build-osx_arm64_python3.11.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.11.____cpythonroot_base6.34.4.yaml"
"inspect-osx_arm64_python3.11.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.11.____cpythonroot_base6.34.4.yaml"
"build-osx_arm64_python3.12.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.12.____cpythonroot_base6.32.10.yaml"
"inspect-osx_arm64_python3.12.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.12.____cpythonroot_base6.32.10.yaml"
"build-osx_arm64_python3.12.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.12.____cpythonroot_base6.34.4.yaml"
"inspect-osx_arm64_python3.12.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.12.____cpythonroot_base6.34.4.yaml"
"build-osx_arm64_python3.9.____cpythonroot_base6.32.10" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.9.____cpythonroot_base6.32.10.yaml"
"inspect-osx_arm64_python3.9.____cpythonroot_base6.32.10" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.9.____cpythonroot_base6.32.10.yaml"
"build-osx_arm64_python3.9.____cpythonroot_base6.34.4" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.9.____cpythonroot_base6.34.4.yaml"
"inspect-osx_arm64_python3.9.____cpythonroot_base6.34.4" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.9.____cpythonroot_base6.34.4.yaml"

[feature.smithy.dependencies]
conda-smithy = "*"

[feature.smithy.tasks]
build-locally = "python ./build-locally.py"
smithy = "conda-smithy"
rerender = "conda-smithy rerender"
lint = "conda-smithy lint recipe"

[environments]
smithy = ["smithy"]
